//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maseya.Smas.Smb1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maseya.Smas.Smb1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Pointer.
        /// </summary>
        internal static string AreaPointer {
            get {
                return ResourceManager.GetString("AreaPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area-specific platform.
        /// </summary>
        internal static string AreaSpecificPlatform {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Bill Shooter.
        /// </summary>
        internal static string AreaSpecificPlatform_BulletBillTurrets {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_BulletBillTurrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Ground.
        /// </summary>
        internal static string AreaSpecificPlatform_CloudGround {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_CloudGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom Platform.
        /// </summary>
        internal static string AreaSpecificPlatform_Mushrooms {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_Mushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Top Platform.
        /// </summary>
        internal static string AreaSpecificPlatform_Trees {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulley Platforms.
        /// </summary>
        internal static string BalanceHorizontalRope {
            get {
                return ResourceManager.GetString("BalanceHorizontalRope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beanstalk.
        /// </summary>
        internal static string Beanstalk {
            get {
                return ResourceManager.GetString("Beanstalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        internal static string Blooper {
            get {
                return ResourceManager.GetString("Blooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser: King of the Koopa.
        /// </summary>
        internal static string Bowser {
            get {
                return ResourceManager.GetString("Bowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser Axe.
        /// </summary>
        internal static string BowserAxe {
            get {
                return ResourceManager.GetString("BowserAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser Bridge.
        /// </summary>
        internal static string BowserBridge {
            get {
                return ResourceManager.GetString("BowserBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser&apos;s Fire.
        /// </summary>
        internal static string BowserFire {
            get {
                return ResourceManager.GetString("BowserFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        internal static string Brick {
            get {
                return ResourceManager.GetString("Brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick and Scenery Change.
        /// </summary>
        internal static string BrickAndSceneryChange {
            get {
                return ResourceManager.GetString("BrickAndSceneryChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope Bridge.
        /// </summary>
        internal static string Bridge {
            get {
                return ResourceManager.GetString("Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Bullet Bill.
        /// </summary>
        internal static string BulletBill {
            get {
                return ResourceManager.GetString("BulletBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator: Bullet Bills.
        /// </summary>
        internal static string BulletBillGenerator {
            get {
                return ResourceManager.GetString("BulletBillGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Bill or Cheep-Cheeps.
        /// </summary>
        internal static string BulletBillOrCheepCheep {
            get {
                return ResourceManager.GetString("BulletBillOrCheepCheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzy Beetle.
        /// </summary>
        internal static string BuzzyBeetle {
            get {
                return ResourceManager.GetString("BuzzyBeetle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle.
        /// </summary>
        internal static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Ceiling Cap Tile.
        /// </summary>
        internal static string CastleCeilingCap {
            get {
                return ResourceManager.GetString("CastleCeilingCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Left-Facing Wall To Floor.
        /// </summary>
        internal static string CastleFloorLeftEdge {
            get {
                return ResourceManager.GetString("CastleFloorLeftEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Left-Facing Wall.
        /// </summary>
        internal static string CastleFloorLeftWall {
            get {
                return ResourceManager.GetString("CastleFloorLeftWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Right-Facing Wall To Floor.
        /// </summary>
        internal static string CastleFloorRightEdge {
            get {
                return ResourceManager.GetString("CastleFloorRightEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Right-Facing Wall.
        /// </summary>
        internal static string CastleFloorRightWall {
            get {
                return ResourceManager.GetString("CastleFloorRightWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Rectangular Ceiling Tiles.
        /// </summary>
        internal static string CastleRectangularCeilingTiles {
            get {
                return ResourceManager.GetString("CastleRectangularCeilingTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Descending Stairs.
        /// </summary>
        internal static string CastleStairs {
            get {
                return ResourceManager.GetString("CastleStairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheep-Cheep.
        /// </summary>
        internal static string CheepCheep {
            get {
                return ResourceManager.GetString("CheepCheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        internal static string Clockwise {
            get {
                return ResourceManager.GetString("Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin.
        /// </summary>
        internal static string Coin {
            get {
                return ResourceManager.GetString("Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Clockwise.
        /// </summary>
        internal static string CounterClockwise {
            get {
                return ResourceManager.GetString("CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashes.
        /// </summary>
        internal static string Crashes {
            get {
                return ResourceManager.GetString("Crashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Tile.
        /// </summary>
        internal static string EmptyTile {
            get {
                return ResourceManager.GetString("EmptyTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterable Pipe.
        /// </summary>
        internal static string EnterablePipe {
            get {
                return ResourceManager.GetString("EnterablePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extendable J-Pipe.
        /// </summary>
        internal static string ExtendableJPipe {
            get {
                return ResourceManager.GetString("ExtendableJPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falling.
        /// </summary>
        internal static string Falling {
            get {
                return ResourceManager.GetString("Falling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Bar.
        /// </summary>
        internal static string FireBar {
            get {
                return ResourceManager.GetString("FireBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Firework.
        /// </summary>
        internal static string Firework {
            get {
                return ResourceManager.GetString("Firework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Pole.
        /// </summary>
        internal static string FlagPole {
            get {
                return ResourceManager.GetString("FlagPole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flies Horizontally.
        /// </summary>
        internal static string FliesHorizontally {
            get {
                return ResourceManager.GetString("FliesHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flies in place.
        /// </summary>
        internal static string FliesInPlace {
            get {
                return ResourceManager.GetString("FliesInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flies Vertically.
        /// </summary>
        internal static string FliesVertically {
            get {
                return ResourceManager.GetString("FliesVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying.
        /// </summary>
        internal static string Flying {
            get {
                return ResourceManager.GetString("Flying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Change.
        /// </summary>
        internal static string ForegroundChange {
            get {
                return ResourceManager.GetString("ForegroundChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goomba.
        /// </summary>
        internal static string Goomba {
            get {
                return ResourceManager.GetString("Goomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Goombas.
        /// </summary>
        internal static string Goomba2 {
            get {
                return ResourceManager.GetString("Goomba2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Goombas.
        /// </summary>
        internal static string Goomba3 {
            get {
                return ResourceManager.GetString("Goomba3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Green Koopa Troopas.
        /// </summary>
        internal static string GreenKoopaTroopa2 {
            get {
                return ResourceManager.GetString("GreenKoopaTroopa2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Green Koopa Troopas.
        /// </summary>
        internal static string GreenKoopaTroopa3 {
            get {
                return ResourceManager.GetString("GreenKoopaTroopa3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer Bros..
        /// </summary>
        internal static string HammerBros {
            get {
                return ResourceManager.GetString("HammerBros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiddenBlock.
        /// </summary>
        internal static string HiddenBlock {
            get {
                return ResourceManager.GetString("HiddenBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole.
        /// </summary>
        internal static string Hole {
            get {
                return ResourceManager.GetString("Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole with water or lava.
        /// </summary>
        internal static string HoleWithWaterOrLava {
            get {
                return ResourceManager.GetString("HoleWithWaterOrLava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Bricks.
        /// </summary>
        internal static string HorizontalBricks {
            get {
                return ResourceManager.GetString("HorizontalBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Coins.
        /// </summary>
        internal static string HorizontalCoins {
            get {
                return ResourceManager.GetString("HorizontalCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width={0}.
        /// </summary>
        internal static string HorizontallyExtendableObject {
            get {
                return ResourceManager.GetString("HorizontallyExtendableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of Coin Blocks.
        /// </summary>
        internal static string HorizontalQuestionBlocks {
            get {
                return ResourceManager.GetString("HorizontalQuestionBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Blocks.
        /// </summary>
        internal static string HorizontalStones {
            get {
                return ResourceManager.GetString("HorizontalStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J-Pipe.
        /// </summary>
        internal static string JPipe {
            get {
                return ResourceManager.GetString("JPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koopa Paratroopa.
        /// </summary>
        internal static string KoopaParatroopa {
            get {
                return ResourceManager.GetString("KoopaParatroopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koopa Troopa.
        /// </summary>
        internal static string KoopaTroopa {
            get {
                return ResourceManager.GetString("KoopaTroopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakitu.
        /// </summary>
        internal static string Lakitu {
            get {
                return ResourceManager.GetString("Lakitu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaping.
        /// </summary>
        internal static string Leaping {
            get {
                return ResourceManager.GetString("Leaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1UP Mushroom.
        /// </summary>
        internal static string LifeMushroom {
            get {
                return ResourceManager.GetString("LifeMushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift.
        /// </summary>
        internal static string Lift {
            get {
                return ResourceManager.GetString("Lift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Loop Command.
        /// </summary>
        internal static string LoopCommand {
            get {
                return ResourceManager.GetString("LoopCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string ObjectWithDescriptor {
            get {
                return ResourceManager.GetString("ObjectWithDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}; {2}; {3}).
        /// </summary>
        internal static string ObjectWithThreeDescriptors {
            get {
                return ResourceManager.GetString("ObjectWithThreeDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}; {2}).
        /// </summary>
        internal static string ObjectWithTwoDescriptors {
            get {
                return ResourceManager.GetString("ObjectWithTwoDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piranha Plant.
        /// </summary>
        internal static string PiranhaPlant {
            get {
                return ResourceManager.GetString("PiranhaPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podoboo.
        /// </summary>
        internal static string Podoboo {
            get {
                return ResourceManager.GetString("Podoboo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerup.
        /// </summary>
        internal static string Powerup {
            get {
                return ResourceManager.GetString("Powerup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope for pulley platforms.
        /// </summary>
        internal static string PulleyRope {
            get {
                return ResourceManager.GetString("PulleyRope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Block.
        /// </summary>
        internal static string QuestionBlock {
            get {
                return ResourceManager.GetString("QuestionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has random speed.
        /// </summary>
        internal static string RandomWalkSpeed {
            get {
                return ResourceManager.GetString("RandomWalkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator: Red flying cheep-cheeps.
        /// </summary>
        internal static string RedCheepCheepFlying {
            get {
                return ResourceManager.GetString("RedCheepCheepFlying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope for axe.
        /// </summary>
        internal static string RopeForAxe {
            get {
                return ResourceManager.GetString("RopeForAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope for platform lifts.
        /// </summary>
        internal static string RopeForLift {
            get {
                return ResourceManager.GetString("RopeForLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Jump.
        /// </summary>
        internal static string ScreenJump {
            get {
                return ResourceManager.GetString("ScreenJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Stop.
        /// </summary>
        internal static string ScrollStop {
            get {
                return ResourceManager.GetString("ScrollStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Stop (Warp Zone).
        /// </summary>
        internal static string ScrollStopWarpZone {
            get {
                return ResourceManager.GetString("ScrollStopWarpZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to screen 0x{0:X2}.
        /// </summary>
        internal static string SetPage {
            get {
                return ResourceManager.GetString("SetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sideways Pipe.
        /// </summary>
        internal static string SidewaysPipe {
            get {
                return ResourceManager.GetString("SidewaysPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiny.
        /// </summary>
        internal static string Spiny {
            get {
                return ResourceManager.GetString("Spiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Board.
        /// </summary>
        internal static string SpringBoard {
            get {
                return ResourceManager.GetString("SpringBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staircase.
        /// </summary>
        internal static string Staircase {
            get {
                return ResourceManager.GetString("Staircase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Generator (also stops Lakitus).
        /// </summary>
        internal static string StopGenerator {
            get {
                return ResourceManager.GetString("StopGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Coins.
        /// </summary>
        internal static string TenCoins {
            get {
                return ResourceManager.GetString("TenCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toad or Princess.
        /// </summary>
        internal static string ToadOrPrincess {
            get {
                return ResourceManager.GetString("ToadOrPrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unenterable Pipe.
        /// </summary>
        internal static string UnenterablePipe {
            get {
                return ResourceManager.GetString("UnenterablePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Block.
        /// </summary>
        internal static string UsedBlock {
            get {
                return ResourceManager.GetString("UsedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Climbing Balls.
        /// </summary>
        internal static string VerticalBalls {
            get {
                return ResourceManager.GetString("VerticalBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Bricks.
        /// </summary>
        internal static string VerticalBricks {
            get {
                return ResourceManager.GetString("VerticalBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height={0}.
        /// </summary>
        internal static string VerticallyExtendableObject {
            get {
                return ResourceManager.GetString("VerticallyExtendableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Sea Blocks.
        /// </summary>
        internal static string VerticalSeaBlocks {
            get {
                return ResourceManager.GetString("VerticalSeaBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Blocks.
        /// </summary>
        internal static string VerticalStones {
            get {
                return ResourceManager.GetString("VerticalStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks in place.
        /// </summary>
        internal static string WalksInPlace {
            get {
                return ResourceManager.GetString("WalksInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks off floors.
        /// </summary>
        internal static string WalksOffFloors {
            get {
                return ResourceManager.GetString("WalksOffFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0}.
        /// </summary>
        internal static string WarningDescriptor {
            get {
                return ResourceManager.GetString("WarningDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: Load Warp Zone.
        /// </summary>
        internal static string WarpZoneCommand {
            get {
                return ResourceManager.GetString("WarpZoneCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y={0}.
        /// </summary>
        internal static string WithSpecificYCoord {
            get {
                return ResourceManager.GetString("WithSpecificYCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koopa Paratroopa (Yellow; Flies in place).
        /// </summary>
        internal static string YellowKoopaParatroopa {
            get {
                return ResourceManager.GetString("YellowKoopaParatroopa", resourceCulture);
            }
        }
    }
}
