//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brutario.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brutario.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alien {
            get {
                object obj = ResourceManager.GetObject("alien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Pole.
        /// </summary>
        internal static string AltFlagPole {
            get {
                return ResourceManager.GetString("AltFlagPole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J-Pipe.
        /// </summary>
        internal static string AltJPipe {
            get {
                return ResourceManager.GetString("AltJPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Stop.
        /// </summary>
        internal static string AltScrollStop {
            get {
                return ResourceManager.GetString("AltScrollStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Bill Shooter (Height={0}).
        /// </summary>
        internal static string AreaSpecificPlatform_BulletBillTurrets {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_BulletBillTurrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Ground (Width={0}).
        /// </summary>
        internal static string AreaSpecificPlatform_CloudGround {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_CloudGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom Platform (Width={0}).
        /// </summary>
        internal static string AreaSpecificPlatform_Mushrooms {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_Mushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Top Platform (Width={0}).
        /// </summary>
        internal static string AreaSpecificPlatform_Trees {
            get {
                return ResourceManager.GetString("AreaSpecificPlatform_Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_rotate_left_solid {
            get {
                object obj = ResourceManager.GetObject("arrow-rotate-left-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_rotate_right_solid {
            get {
                object obj = ResourceManager.GetObject("arrow-rotate-right-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulley Platforms (Width={0}).
        /// </summary>
        internal static string BalanceHorizontalRope {
            get {
                return ResourceManager.GetString("BalanceHorizontalRope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser Axe.
        /// </summary>
        internal static string BowserAxe {
            get {
                return ResourceManager.GetString("BowserAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser Bridge.
        /// </summary>
        internal static string BowserBridge {
            get {
                return ResourceManager.GetString("BowserBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick (10 Coins).
        /// </summary>
        internal static string Brick10Coins {
            get {
                return ResourceManager.GetString("Brick10Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick (1UP).
        /// </summary>
        internal static string Brick1UP {
            get {
                return ResourceManager.GetString("Brick1UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick and Scenery Change.
        /// </summary>
        internal static string BrickAndSceneryChange {
            get {
                return ResourceManager.GetString("BrickAndSceneryChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick (Beanstalk).
        /// </summary>
        internal static string BrickBeanstalk {
            get {
                return ResourceManager.GetString("BrickBeanstalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick (Powerup).
        /// </summary>
        internal static string BrickPowerup {
            get {
                return ResourceManager.GetString("BrickPowerup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick (Star).
        /// </summary>
        internal static string BrickStar {
            get {
                return ResourceManager.GetString("BrickStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope Bridge (Y=10, Width={0}).
        /// </summary>
        internal static string BridgeV10 {
            get {
                return ResourceManager.GetString("BridgeV10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope Bridge (Y=7, Width={0}).
        /// </summary>
        internal static string BridgeV7 {
            get {
                return ResourceManager.GetString("BridgeV7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope Bridge (Y=8, Width={0}).
        /// </summary>
        internal static string BridgeV8 {
            get {
                return ResourceManager.GetString("BridgeV8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator: Bullet Bills.
        /// </summary>
        internal static string BulletBillGenerator {
            get {
                return ResourceManager.GetString("BulletBillGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle.
        /// </summary>
        internal static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Ceiling Cap Tile.
        /// </summary>
        internal static string CastleCeilingCap {
            get {
                return ResourceManager.GetString("CastleCeilingCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Left-Facing Wall To Floor.
        /// </summary>
        internal static string CastleFloorLeftEdge {
            get {
                return ResourceManager.GetString("CastleFloorLeftEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Left-Facing Wall.
        /// </summary>
        internal static string CastleFloorLeftWall {
            get {
                return ResourceManager.GetString("CastleFloorLeftWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Right-Facing Wall To Floor.
        /// </summary>
        internal static string CastleFloorRightEdge {
            get {
                return ResourceManager.GetString("CastleFloorRightEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Right-Facing Wall.
        /// </summary>
        internal static string CastleFloorRightWall {
            get {
                return ResourceManager.GetString("CastleFloorRightWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Rectangular Ceiling Tiles.
        /// </summary>
        internal static string CastleRectangularCeilingTiles {
            get {
                return ResourceManager.GetString("CastleRectangularCeilingTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Object: Descending Stairs.
        /// </summary>
        internal static string CastleStairs {
            get {
                return ResourceManager.GetString("CastleStairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circle_question_regular {
            get {
                object obj = ResourceManager.GetObject("circle-question-regular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_regular {
            get {
                object obj = ResourceManager.GetObject("copy-regular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Credits {
            get {
                object obj = ResourceManager.GetObject("Credits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string Empty2 {
            get {
                return ResourceManager.GetString("Empty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Tile.
        /// </summary>
        internal static string EmptyTile {
            get {
                return ResourceManager.GetString("EmptyTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterable Pipe (Height={0}).
        /// </summary>
        internal static string EnterablePipe {
            get {
                return ResourceManager.GetString("EnterablePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extendable J-Pipe (Height={0}).
        /// </summary>
        internal static string ExtendableJPipe {
            get {
                return ResourceManager.GetString("ExtendableJPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Pole.
        /// </summary>
        internal static string FlagPole {
            get {
                return ResourceManager.GetString("FlagPole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disk_regular {
            get {
                object obj = ResourceManager.GetObject("floppy-disk-regular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_multiple_solid {
            get {
                object obj = ResourceManager.GetObject("folder-multiple-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_solid {
            get {
                object obj = ResourceManager.GetObject("folder-open-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_tree_solid {
            get {
                object obj = ResourceManager.GetObject("folder-tree-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Change.
        /// </summary>
        internal static string ForegroundChange {
            get {
                return ResourceManager.GetString("ForegroundChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gamepad_solid {
            get {
                object obj = ResourceManager.GetObject("gamepad-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear_solid {
            get {
                object obj = ResourceManager.GetObject("gear-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hands_clapping_solid {
            get {
                object obj = ResourceManager.GetObject("hands-clapping-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Block (1UP).
        /// </summary>
        internal static string HiddenBlock1UP {
            get {
                return ResourceManager.GetString("HiddenBlock1UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Block (Coin).
        /// </summary>
        internal static string HiddenBlockCoin {
            get {
                return ResourceManager.GetString("HiddenBlockCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole (Width={0}).
        /// </summary>
        internal static string Hole {
            get {
                return ResourceManager.GetString("Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole with water or lava (Width={0}).
        /// </summary>
        internal static string HoleWithWaterOrLava {
            get {
                return ResourceManager.GetString("HoleWithWaterOrLava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Bricks (Width={0}).
        /// </summary>
        internal static string HorizontalBricks {
            get {
                return ResourceManager.GetString("HorizontalBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Coins (Width={0}).
        /// </summary>
        internal static string HorizontalCoins {
            get {
                return ResourceManager.GetString("HorizontalCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of Coin Blocks (Y=3, Width={0}).
        /// </summary>
        internal static string HorizontalQuestionBlocksV3 {
            get {
                return ResourceManager.GetString("HorizontalQuestionBlocksV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row of Coin Blocks (Y=7, Width={0}).
        /// </summary>
        internal static string HorizontalQuestionBlocksV7 {
            get {
                return ResourceManager.GetString("HorizontalQuestionBlocksV7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Blocks (Width={0}).
        /// </summary>
        internal static string HorizontalStones {
            get {
                return ResourceManager.GetString("HorizontalStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J-Pipe.
        /// </summary>
        internal static string JPipe {
            get {
                return ResourceManager.GetString("JPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Loop Command.
        /// </summary>
        internal static string LoopCommand {
            get {
                return ResourceManager.GetString("LoopCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_regular {
            get {
                object obj = ResourceManager.GetObject("map-regular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap microchip_solid {
            get {
                object obj = ResourceManager.GetObject("microchip-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus_solid {
            get {
                object obj = ResourceManager.GetObject("minus-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_regular {
            get {
                object obj = ResourceManager.GetObject("paste-regular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_solid {
            get {
                object obj = ResourceManager.GetObject("plus-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope for pulley platforms (Height={0}).
        /// </summary>
        internal static string PulleyRope {
            get {
                return ResourceManager.GetString("PulleyRope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Block (Coin).
        /// </summary>
        internal static string QuestionBlockCoin {
            get {
                return ResourceManager.GetString("QuestionBlockCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Block (Powerup).
        /// </summary>
        internal static string QuestionBlockPowerup {
            get {
                return ResourceManager.GetString("QuestionBlockPowerup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator: Red flying cheep-cheeps.
        /// </summary>
        internal static string RedCheepCheepFlying {
            get {
                return ResourceManager.GetString("RedCheepCheepFlying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rope for platform lifts.
        /// </summary>
        internal static string RopeForLift {
            get {
                return ResourceManager.GetString("RopeForLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scissors_solid {
            get {
                object obj = ResourceManager.GetObject("scissors-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to screen 0x{1:X2}.
        /// </summary>
        internal static string ScreenJump {
            get {
                return ResourceManager.GetString("ScreenJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Stop.
        /// </summary>
        internal static string ScrollStop {
            get {
                return ResourceManager.GetString("ScrollStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Stop (Warp Zone).
        /// </summary>
        internal static string ScrollStopWarpZone {
            get {
                return ResourceManager.GetString("ScrollStopWarpZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sideways Pipe.
        /// </summary>
        internal static string SidewaysPipe {
            get {
                return ResourceManager.GetString("SidewaysPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Board.
        /// </summary>
        internal static string SpringBoard {
            get {
                return ResourceManager.GetString("SpringBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staircase (Width={0}).
        /// </summary>
        internal static string Staircase {
            get {
                return ResourceManager.GetString("Staircase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Generator (also stops Lakitus).
        /// </summary>
        internal static string StopGenerator {
            get {
                return ResourceManager.GetString("StopGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash_can_solid {
            get {
                object obj = ResourceManager.GetObject("trash-can-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unenterable Pipe (Height={0}).
        /// </summary>
        internal static string UnenterablePipe {
            get {
                return ResourceManager.GetString("UnenterablePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {2}.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Block.
        /// </summary>
        internal static string UsedBlock {
            get {
                return ResourceManager.GetString("UsedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Climbing Balls (Height={0}).
        /// </summary>
        internal static string VerticalBalls {
            get {
                return ResourceManager.GetString("VerticalBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Bricks (Height={0}).
        /// </summary>
        internal static string VerticalBricks {
            get {
                return ResourceManager.GetString("VerticalBricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Sea Blocks (Height={0}).
        /// </summary>
        internal static string VerticalSeaBlocks {
            get {
                return ResourceManager.GetString("VerticalSeaBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Blocks (Height={0}).
        /// </summary>
        internal static string VerticalStones {
            get {
                return ResourceManager.GetString("VerticalStones", resourceCulture);
            }
        }
    }
}
